/********************************************************************************
** Form generated from reading UI file 'frm_object_calibration.ui'
**
** Created by: Qt User Interface Compiler version 5.9.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_FRM_OBJECT_CALIBRATION_H
#define UI_FRM_OBJECT_CALIBRATION_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTextEdit>

QT_BEGIN_NAMESPACE

class Ui_C_frm_object_calibration
{
public:
    QLabel *lbl_src_img;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *lbl_img_contoured;
    QGroupBox *groupBox;
    QSpinBox *num_opening_iterations;
    QSpinBox *num_closing_iterations;
    QSpinBox *num_closing_iterations_2;
    QSpinBox *num_closing_iterations_3;
    QSpinBox *num_closing_iterations_4;
    QSpinBox *num_morph_kernelsize;
    QSpinBox *num_dilate_kernelsize;
    QSpinBox *num_erode_kernelsize;
    QSpinBox *num_closing_kernelsize;
    QSpinBox *num_opening_kernelsize;
    QLabel *label;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QSpinBox *num_gaussian_sigma;
    QSpinBox *num_sigma_kernelsize;
    QSpinBox *num_bilateral_kernelsize;
    QSpinBox *num_bilateral_spatial;
    QSpinBox *num_bilateral_color;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QGroupBox *groupBox_2;
    QSlider *sld_hue_min;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QSlider *sld_hue_max;
    QTextEdit *txb_hue_min;
    QTextEdit *txb_hue_max;
    QTextEdit *txb_saturation_min;
    QLabel *label_20;
    QSlider *sld_saturation_max;
    QTextEdit *txb_saturation_max;
    QLabel *label_21;
    QSlider *sld_saturation_min;
    QLabel *label_22;
    QSlider *sld_value_max;
    QTextEdit *txb_value_min;
    QTextEdit *txb_value_max;
    QLabel *label_23;
    QSlider *sld_value_min;
    QSlider *sld_objectsize_min;
    QLabel *label_24;
    QTextEdit *txb_objectsize_min;
    QLabel *label_25;
    QSlider *sld_objectsize_max;
    QTextEdit *txb_objectsize_max;
    QLabel *label_26;
    QGroupBox *groupBox_3;
    QLabel *label_27;
    QLabel *label_28;
    QTextEdit *txb_s_x;
    QTextEdit *txb_s_y;
    QTextEdit *txb_delta_y;
    QLabel *label_29;
    QTextEdit *txb_delta_x;
    QLabel *label_30;
    QLabel *label_31;
    QTextEdit *txb_timestamp;
    QLabel *label_33;
    QLabel *label_34;
    QTextEdit *txb_frametime;
    QTextEdit *txb_fps;
    QSpinBox *num_camera;
    QLabel *label_32;
    QPushButton *bt_exit;
    QTextEdit *txb_zaehler;

    void setupUi(QDialog *C_frm_object_calibration)
    {
        if (C_frm_object_calibration->objectName().isEmpty())
            C_frm_object_calibration->setObjectName(QStringLiteral("C_frm_object_calibration"));
        C_frm_object_calibration->resize(1567, 832);
        lbl_src_img = new QLabel(C_frm_object_calibration);
        lbl_src_img->setObjectName(QStringLiteral("lbl_src_img"));
        lbl_src_img->setGeometry(QRect(40, 20, 341, 291));
        label_2 = new QLabel(C_frm_object_calibration);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(410, 20, 341, 291));
        label_3 = new QLabel(C_frm_object_calibration);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(760, 20, 341, 291));
        lbl_img_contoured = new QLabel(C_frm_object_calibration);
        lbl_img_contoured->setObjectName(QStringLiteral("lbl_img_contoured"));
        lbl_img_contoured->setGeometry(QRect(1120, 20, 341, 291));
        groupBox = new QGroupBox(C_frm_object_calibration);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(40, 320, 321, 441));
        num_opening_iterations = new QSpinBox(groupBox);
        num_opening_iterations->setObjectName(QStringLiteral("num_opening_iterations"));
        num_opening_iterations->setGeometry(QRect(110, 70, 51, 31));
        QFont font;
        font.setPointSize(14);
        num_opening_iterations->setFont(font);
        num_closing_iterations = new QSpinBox(groupBox);
        num_closing_iterations->setObjectName(QStringLiteral("num_closing_iterations"));
        num_closing_iterations->setGeometry(QRect(110, 110, 51, 31));
        num_closing_iterations->setFont(font);
        num_closing_iterations_2 = new QSpinBox(groupBox);
        num_closing_iterations_2->setObjectName(QStringLiteral("num_closing_iterations_2"));
        num_closing_iterations_2->setGeometry(QRect(110, 150, 51, 31));
        num_closing_iterations_2->setFont(font);
        num_closing_iterations_3 = new QSpinBox(groupBox);
        num_closing_iterations_3->setObjectName(QStringLiteral("num_closing_iterations_3"));
        num_closing_iterations_3->setGeometry(QRect(110, 190, 51, 31));
        num_closing_iterations_3->setFont(font);
        num_closing_iterations_4 = new QSpinBox(groupBox);
        num_closing_iterations_4->setObjectName(QStringLiteral("num_closing_iterations_4"));
        num_closing_iterations_4->setGeometry(QRect(110, 230, 51, 31));
        num_closing_iterations_4->setFont(font);
        num_morph_kernelsize = new QSpinBox(groupBox);
        num_morph_kernelsize->setObjectName(QStringLiteral("num_morph_kernelsize"));
        num_morph_kernelsize->setGeometry(QRect(230, 230, 51, 31));
        num_morph_kernelsize->setFont(font);
        num_dilate_kernelsize = new QSpinBox(groupBox);
        num_dilate_kernelsize->setObjectName(QStringLiteral("num_dilate_kernelsize"));
        num_dilate_kernelsize->setGeometry(QRect(230, 190, 51, 31));
        num_dilate_kernelsize->setFont(font);
        num_erode_kernelsize = new QSpinBox(groupBox);
        num_erode_kernelsize->setObjectName(QStringLiteral("num_erode_kernelsize"));
        num_erode_kernelsize->setGeometry(QRect(230, 150, 51, 31));
        num_erode_kernelsize->setFont(font);
        num_closing_kernelsize = new QSpinBox(groupBox);
        num_closing_kernelsize->setObjectName(QStringLiteral("num_closing_kernelsize"));
        num_closing_kernelsize->setGeometry(QRect(230, 110, 51, 31));
        num_closing_kernelsize->setFont(font);
        num_opening_kernelsize = new QSpinBox(groupBox);
        num_opening_kernelsize->setObjectName(QStringLiteral("num_opening_kernelsize"));
        num_opening_kernelsize->setGeometry(QRect(230, 70, 51, 31));
        num_opening_kernelsize->setFont(font);
        label = new QLabel(groupBox);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(210, 40, 101, 20));
        label->setFont(font);
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(100, 40, 91, 20));
        label_4->setFont(font);
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(20, 80, 91, 20));
        label_5->setFont(font);
        label_6 = new QLabel(groupBox);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(20, 120, 91, 20));
        label_6->setFont(font);
        label_7 = new QLabel(groupBox);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(20, 160, 61, 20));
        label_7->setFont(font);
        label_8 = new QLabel(groupBox);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(20, 200, 51, 20));
        label_8->setFont(font);
        label_9 = new QLabel(groupBox);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(20, 240, 61, 20));
        label_9->setFont(font);
        label_10 = new QLabel(groupBox);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(110, 270, 61, 20));
        label_10->setFont(font);
        label_11 = new QLabel(groupBox);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(20, 310, 81, 20));
        label_11->setFont(font);
        num_gaussian_sigma = new QSpinBox(groupBox);
        num_gaussian_sigma->setObjectName(QStringLiteral("num_gaussian_sigma"));
        num_gaussian_sigma->setGeometry(QRect(110, 300, 51, 31));
        num_gaussian_sigma->setFont(font);
        num_sigma_kernelsize = new QSpinBox(groupBox);
        num_sigma_kernelsize->setObjectName(QStringLiteral("num_sigma_kernelsize"));
        num_sigma_kernelsize->setGeometry(QRect(230, 300, 51, 31));
        num_sigma_kernelsize->setFont(font);
        num_bilateral_kernelsize = new QSpinBox(groupBox);
        num_bilateral_kernelsize->setObjectName(QStringLiteral("num_bilateral_kernelsize"));
        num_bilateral_kernelsize->setGeometry(QRect(230, 390, 51, 31));
        num_bilateral_kernelsize->setFont(font);
        num_bilateral_spatial = new QSpinBox(groupBox);
        num_bilateral_spatial->setObjectName(QStringLiteral("num_bilateral_spatial"));
        num_bilateral_spatial->setGeometry(QRect(160, 390, 51, 31));
        num_bilateral_spatial->setFont(font);
        num_bilateral_color = new QSpinBox(groupBox);
        num_bilateral_color->setObjectName(QStringLiteral("num_bilateral_color"));
        num_bilateral_color->setGeometry(QRect(100, 390, 51, 31));
        num_bilateral_color->setFont(font);
        label_12 = new QLabel(groupBox);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(100, 370, 51, 20));
        label_12->setFont(font);
        label_13 = new QLabel(groupBox);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(160, 370, 61, 20));
        label_13->setFont(font);
        label_14 = new QLabel(groupBox);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(20, 400, 81, 20));
        label_14->setFont(font);
        groupBox_2 = new QGroupBox(C_frm_object_calibration);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(380, 320, 461, 441));
        sld_hue_min = new QSlider(groupBox_2);
        sld_hue_min->setObjectName(QStringLiteral("sld_hue_min"));
        sld_hue_min->setGeometry(QRect(100, 61, 231, 16));
        sld_hue_min->setOrientation(Qt::Horizontal);
        label_15 = new QLabel(groupBox_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(10, 30, 91, 20));
        label_15->setFont(font);
        label_16 = new QLabel(groupBox_2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(10, 140, 91, 20));
        label_16->setFont(font);
        label_17 = new QLabel(groupBox_2);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(10, 240, 91, 20));
        label_17->setFont(font);
        label_18 = new QLabel(groupBox_2);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(60, 60, 41, 21));
        QFont font1;
        font1.setPointSize(11);
        label_18->setFont(font1);
        label_19 = new QLabel(groupBox_2);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(60, 100, 41, 21));
        label_19->setFont(font1);
        sld_hue_max = new QSlider(groupBox_2);
        sld_hue_max->setObjectName(QStringLiteral("sld_hue_max"));
        sld_hue_max->setGeometry(QRect(100, 100, 231, 16));
        sld_hue_max->setOrientation(Qt::Horizontal);
        txb_hue_min = new QTextEdit(groupBox_2);
        txb_hue_min->setObjectName(QStringLiteral("txb_hue_min"));
        txb_hue_min->setGeometry(QRect(340, 50, 104, 31));
        txb_hue_min->setFont(font1);
        txb_hue_min->setReadOnly(true);
        txb_hue_max = new QTextEdit(groupBox_2);
        txb_hue_max->setObjectName(QStringLiteral("txb_hue_max"));
        txb_hue_max->setGeometry(QRect(340, 90, 104, 31));
        txb_hue_max->setFont(font1);
        txb_hue_max->setReadOnly(true);
        txb_saturation_min = new QTextEdit(groupBox_2);
        txb_saturation_min->setObjectName(QStringLiteral("txb_saturation_min"));
        txb_saturation_min->setGeometry(QRect(340, 159, 104, 31));
        txb_saturation_min->setFont(font1);
        txb_saturation_min->setReadOnly(true);
        label_20 = new QLabel(groupBox_2);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(60, 209, 41, 21));
        label_20->setFont(font1);
        sld_saturation_max = new QSlider(groupBox_2);
        sld_saturation_max->setObjectName(QStringLiteral("sld_saturation_max"));
        sld_saturation_max->setGeometry(QRect(100, 209, 231, 16));
        sld_saturation_max->setOrientation(Qt::Horizontal);
        txb_saturation_max = new QTextEdit(groupBox_2);
        txb_saturation_max->setObjectName(QStringLiteral("txb_saturation_max"));
        txb_saturation_max->setGeometry(QRect(340, 199, 104, 31));
        txb_saturation_max->setFont(font1);
        txb_saturation_max->setReadOnly(true);
        label_21 = new QLabel(groupBox_2);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(60, 169, 41, 21));
        label_21->setFont(font1);
        sld_saturation_min = new QSlider(groupBox_2);
        sld_saturation_min->setObjectName(QStringLiteral("sld_saturation_min"));
        sld_saturation_min->setGeometry(QRect(100, 170, 231, 16));
        sld_saturation_min->setOrientation(Qt::Horizontal);
        label_22 = new QLabel(groupBox_2);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(60, 269, 41, 21));
        label_22->setFont(font1);
        sld_value_max = new QSlider(groupBox_2);
        sld_value_max->setObjectName(QStringLiteral("sld_value_max"));
        sld_value_max->setGeometry(QRect(100, 309, 231, 16));
        sld_value_max->setOrientation(Qt::Horizontal);
        txb_value_min = new QTextEdit(groupBox_2);
        txb_value_min->setObjectName(QStringLiteral("txb_value_min"));
        txb_value_min->setGeometry(QRect(340, 259, 104, 31));
        txb_value_min->setFont(font1);
        txb_value_min->setReadOnly(true);
        txb_value_max = new QTextEdit(groupBox_2);
        txb_value_max->setObjectName(QStringLiteral("txb_value_max"));
        txb_value_max->setGeometry(QRect(340, 299, 104, 31));
        txb_value_max->setFont(font1);
        txb_value_max->setReadOnly(true);
        label_23 = new QLabel(groupBox_2);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(60, 309, 41, 21));
        label_23->setFont(font1);
        sld_value_min = new QSlider(groupBox_2);
        sld_value_min->setObjectName(QStringLiteral("sld_value_min"));
        sld_value_min->setGeometry(QRect(100, 270, 231, 16));
        sld_value_min->setOrientation(Qt::Horizontal);
        sld_objectsize_min = new QSlider(groupBox_2);
        sld_objectsize_min->setObjectName(QStringLiteral("sld_objectsize_min"));
        sld_objectsize_min->setGeometry(QRect(100, 371, 231, 16));
        sld_objectsize_min->setOrientation(Qt::Horizontal);
        label_24 = new QLabel(groupBox_2);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(10, 341, 111, 20));
        label_24->setFont(font);
        txb_objectsize_min = new QTextEdit(groupBox_2);
        txb_objectsize_min->setObjectName(QStringLiteral("txb_objectsize_min"));
        txb_objectsize_min->setGeometry(QRect(340, 360, 104, 31));
        txb_objectsize_min->setFont(font1);
        txb_objectsize_min->setReadOnly(true);
        label_25 = new QLabel(groupBox_2);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(60, 410, 41, 21));
        label_25->setFont(font1);
        sld_objectsize_max = new QSlider(groupBox_2);
        sld_objectsize_max->setObjectName(QStringLiteral("sld_objectsize_max"));
        sld_objectsize_max->setGeometry(QRect(100, 410, 231, 16));
        sld_objectsize_max->setOrientation(Qt::Horizontal);
        txb_objectsize_max = new QTextEdit(groupBox_2);
        txb_objectsize_max->setObjectName(QStringLiteral("txb_objectsize_max"));
        txb_objectsize_max->setGeometry(QRect(340, 400, 104, 31));
        txb_objectsize_max->setFont(font1);
        txb_objectsize_max->setReadOnly(true);
        label_26 = new QLabel(groupBox_2);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(60, 370, 41, 21));
        label_26->setFont(font1);
        groupBox_3 = new QGroupBox(C_frm_object_calibration);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(860, 320, 241, 321));
        label_27 = new QLabel(groupBox_3);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(20, 40, 41, 21));
        label_27->setFont(font1);
        label_28 = new QLabel(groupBox_3);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(20, 80, 41, 21));
        label_28->setFont(font1);
        txb_s_x = new QTextEdit(groupBox_3);
        txb_s_x->setObjectName(QStringLiteral("txb_s_x"));
        txb_s_x->setGeometry(QRect(90, 30, 104, 31));
        txb_s_x->setFont(font1);
        txb_s_x->setReadOnly(true);
        txb_s_y = new QTextEdit(groupBox_3);
        txb_s_y->setObjectName(QStringLiteral("txb_s_y"));
        txb_s_y->setGeometry(QRect(90, 70, 104, 31));
        txb_s_y->setFont(font1);
        txb_s_y->setReadOnly(true);
        txb_delta_y = new QTextEdit(groupBox_3);
        txb_delta_y->setObjectName(QStringLiteral("txb_delta_y"));
        txb_delta_y->setGeometry(QRect(90, 150, 104, 31));
        txb_delta_y->setFont(font1);
        txb_delta_y->setReadOnly(true);
        label_29 = new QLabel(groupBox_3);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(20, 120, 51, 21));
        label_29->setFont(font1);
        txb_delta_x = new QTextEdit(groupBox_3);
        txb_delta_x->setObjectName(QStringLiteral("txb_delta_x"));
        txb_delta_x->setGeometry(QRect(90, 110, 104, 31));
        txb_delta_x->setFont(font1);
        txb_delta_x->setReadOnly(true);
        label_30 = new QLabel(groupBox_3);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(20, 160, 61, 21));
        label_30->setFont(font1);
        label_31 = new QLabel(groupBox_3);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(10, 200, 81, 21));
        label_31->setFont(font1);
        txb_timestamp = new QTextEdit(groupBox_3);
        txb_timestamp->setObjectName(QStringLiteral("txb_timestamp"));
        txb_timestamp->setGeometry(QRect(90, 190, 104, 31));
        txb_timestamp->setFont(font1);
        txb_timestamp->setReadOnly(true);
        label_33 = new QLabel(groupBox_3);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(10, 280, 81, 21));
        label_33->setFont(font1);
        label_34 = new QLabel(groupBox_3);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(10, 240, 81, 21));
        label_34->setFont(font1);
        txb_frametime = new QTextEdit(groupBox_3);
        txb_frametime->setObjectName(QStringLiteral("txb_frametime"));
        txb_frametime->setGeometry(QRect(90, 230, 104, 31));
        txb_frametime->setFont(font1);
        txb_frametime->setReadOnly(true);
        txb_fps = new QTextEdit(groupBox_3);
        txb_fps->setObjectName(QStringLiteral("txb_fps"));
        txb_fps->setGeometry(QRect(90, 270, 104, 31));
        txb_fps->setFont(font1);
        txb_fps->setReadOnly(true);
        num_camera = new QSpinBox(C_frm_object_calibration);
        num_camera->setObjectName(QStringLiteral("num_camera"));
        num_camera->setGeometry(QRect(1410, 650, 71, 41));
        num_camera->setFont(font);
        label_32 = new QLabel(C_frm_object_calibration);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(1410, 620, 101, 21));
        label_32->setFont(font);
        bt_exit = new QPushButton(C_frm_object_calibration);
        bt_exit->setObjectName(QStringLiteral("bt_exit"));
        bt_exit->setGeometry(QRect(1410, 750, 141, 71));
        txb_zaehler = new QTextEdit(C_frm_object_calibration);
        txb_zaehler->setObjectName(QStringLiteral("txb_zaehler"));
        txb_zaehler->setGeometry(QRect(1410, 710, 141, 31));
        txb_zaehler->setReadOnly(true);

        retranslateUi(C_frm_object_calibration);

        QMetaObject::connectSlotsByName(C_frm_object_calibration);
    } // setupUi

    void retranslateUi(QDialog *C_frm_object_calibration)
    {
        C_frm_object_calibration->setWindowTitle(QApplication::translate("C_frm_object_calibration", "Dialog", Q_NULLPTR));
        lbl_src_img->setText(QApplication::translate("C_frm_object_calibration", "Originalbild", Q_NULLPTR));
        label_2->setText(QApplication::translate("C_frm_object_calibration", "Originalbild", Q_NULLPTR));
        label_3->setText(QApplication::translate("C_frm_object_calibration", "Originalbild", Q_NULLPTR));
        lbl_img_contoured->setText(QApplication::translate("C_frm_object_calibration", "Originalbild", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("C_frm_object_calibration", "Filtering", Q_NULLPTR));
        label->setText(QApplication::translate("C_frm_object_calibration", "Kernel Size", Q_NULLPTR));
        label_4->setText(QApplication::translate("C_frm_object_calibration", "Iterations", Q_NULLPTR));
        label_5->setText(QApplication::translate("C_frm_object_calibration", "Opening", Q_NULLPTR));
        label_6->setText(QApplication::translate("C_frm_object_calibration", "Closing", Q_NULLPTR));
        label_7->setText(QApplication::translate("C_frm_object_calibration", "Erode", Q_NULLPTR));
        label_8->setText(QApplication::translate("C_frm_object_calibration", "Dilate", Q_NULLPTR));
        label_9->setText(QApplication::translate("C_frm_object_calibration", "Morph", Q_NULLPTR));
        label_10->setText(QApplication::translate("C_frm_object_calibration", "Sigma", Q_NULLPTR));
        label_11->setText(QApplication::translate("C_frm_object_calibration", "Gaussian", Q_NULLPTR));
        label_12->setText(QApplication::translate("C_frm_object_calibration", "Color", Q_NULLPTR));
        label_13->setText(QApplication::translate("C_frm_object_calibration", "Spatial", Q_NULLPTR));
        label_14->setText(QApplication::translate("C_frm_object_calibration", "Bilateral", Q_NULLPTR));
        groupBox_2->setTitle(QApplication::translate("C_frm_object_calibration", "HSV-Filter", Q_NULLPTR));
        label_15->setText(QApplication::translate("C_frm_object_calibration", "Hue", Q_NULLPTR));
        label_16->setText(QApplication::translate("C_frm_object_calibration", "Saturation", Q_NULLPTR));
        label_17->setText(QApplication::translate("C_frm_object_calibration", "Value", Q_NULLPTR));
        label_18->setText(QApplication::translate("C_frm_object_calibration", "min", Q_NULLPTR));
        label_19->setText(QApplication::translate("C_frm_object_calibration", "max", Q_NULLPTR));
        label_20->setText(QApplication::translate("C_frm_object_calibration", "max", Q_NULLPTR));
        label_21->setText(QApplication::translate("C_frm_object_calibration", "min", Q_NULLPTR));
        label_22->setText(QApplication::translate("C_frm_object_calibration", "min", Q_NULLPTR));
        label_23->setText(QApplication::translate("C_frm_object_calibration", "max", Q_NULLPTR));
        label_24->setText(QApplication::translate("C_frm_object_calibration", "Objektgr\303\266\303\237e", Q_NULLPTR));
        label_25->setText(QApplication::translate("C_frm_object_calibration", "max", Q_NULLPTR));
        label_26->setText(QApplication::translate("C_frm_object_calibration", "min", Q_NULLPTR));
        groupBox_3->setTitle(QApplication::translate("C_frm_object_calibration", "Image Data", Q_NULLPTR));
        label_27->setText(QApplication::translate("C_frm_object_calibration", "S_x", Q_NULLPTR));
        label_28->setText(QApplication::translate("C_frm_object_calibration", "S_y", Q_NULLPTR));
        label_29->setText(QApplication::translate("C_frm_object_calibration", "Delta_x", Q_NULLPTR));
        label_30->setText(QApplication::translate("C_frm_object_calibration", "Delta_y", Q_NULLPTR));
        label_31->setText(QApplication::translate("C_frm_object_calibration", "Timestamp", Q_NULLPTR));
        label_33->setText(QApplication::translate("C_frm_object_calibration", "FPS", Q_NULLPTR));
        label_34->setText(QApplication::translate("C_frm_object_calibration", "Frametime", Q_NULLPTR));
        label_32->setText(QApplication::translate("C_frm_object_calibration", "Kamera", Q_NULLPTR));
        bt_exit->setText(QApplication::translate("C_frm_object_calibration", "Exit", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class C_frm_object_calibration: public Ui_C_frm_object_calibration {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_FRM_OBJECT_CALIBRATION_H
